# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright The Lance Authors

from typing import Iterable, Iterator, Optional, Union

import pyarrow as pa

class Bitmap:
    """
    A set of non-negative integers backed by a Rust ``RoaringBitmap``.

    Cheap to clone and to pass into Lance APIs that accept a bitmap, since no
    per-value Python object is created. Mutating methods (``add``,
    ``discard``, ``update``, ...) copy-on-write: cloning a ``Bitmap`` and
    mutating one copy never affects the other.

    Implements the ``collections.abc.MutableSet`` interface and is registered
    as one, so ``isinstance(b, collections.abc.Set)`` holds.
    ``isinstance(b, set)`` does not: it is a distinct type, not a ``set``
    subclass.

    Anywhere a ``Bitmap`` accepts another set, it also accepts any iterable of
    ints; order and repeats in that iterable are not significant.
    """

    def __init__(
        self,
        values: Optional[
            Union[Iterable[int], pa.Array, pa.ChunkedArray, "Bitmap"]
        ] = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __le__(self, other: Iterable[int]) -> bool: ...
    def __lt__(self, other: Iterable[int]) -> bool: ...
    def __ge__(self, other: Iterable[int]) -> bool: ...
    def __gt__(self, other: Iterable[int]) -> bool: ...
    def __and__(self, other: Iterable[int]) -> "Bitmap": ...
    def __rand__(self, other: Iterable[int]) -> "Bitmap": ...
    def __or__(self, other: Iterable[int]) -> "Bitmap": ...
    def __ror__(self, other: Iterable[int]) -> "Bitmap": ...
    def __sub__(self, other: Iterable[int]) -> "Bitmap": ...
    def __rsub__(self, other: Iterable[int]) -> "Bitmap": ...
    def __xor__(self, other: Iterable[int]) -> "Bitmap": ...
    def __rxor__(self, other: Iterable[int]) -> "Bitmap": ...
    def __iand__(self, other: Iterable[int]) -> "Bitmap": ...
    def __ior__(self, other: Iterable[int]) -> "Bitmap": ...
    def __isub__(self, other: Iterable[int]) -> "Bitmap": ...
    def __ixor__(self, other: Iterable[int]) -> "Bitmap": ...
    def intersection(self, other: Iterable[int]) -> "Bitmap": ...
    def union(self, other: Iterable[int]) -> "Bitmap": ...
    def difference(self, other: Iterable[int]) -> "Bitmap": ...
    def symmetric_difference(self, other: Iterable[int]) -> "Bitmap": ...
    def issubset(self, other: Iterable[int]) -> bool: ...
    def issuperset(self, other: Iterable[int]) -> bool: ...
    def isdisjoint(self, other: Iterable[int]) -> bool: ...
    def copy(self) -> "Bitmap": ...
    def add(self, value: int) -> None: ...
    def discard(self, value: int) -> None: ...
    def remove(self, value: int) -> None: ...
    def pop(self) -> int: ...
    def clear(self) -> None: ...
    def update(self, values: Iterable[int]) -> None: ...
